/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "view_data.h"
#include "uib_app_manager.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include "sensor_params.h"
#include <sensor.h>
#include <device/power.h>

#define FONT_SIZE 20

#define SERVICE_APP_NAME "org.example.rawsensordata"

unsigned long long get_fileSize(){
	char fpath[256];
	strcpy(fpath, app_get_data_path());
	strcat(fpath, "ppg_data.csv");
	FILE* fp = fopen(fpath, "r");
	if(fp) {
		unsigned long long filesize = ftell(fp);
		fclose(fp);
		return filesize;
	}
	return -1;
}

const char* get_dataSize(char *fsize){
	char fpath[256];
	sprintf(fpath, "du -sh %s | cut -f 1", app_get_data_path());
	FILE* fp = popen(fpath, "r");
	if(fp) {
		fscanf(fp, "%s", fsize);
		pclose(fp);
		return fsize;
	}
	return NULL;
}

static void launch_service()
{
	dlog_print(DLOG_ERROR, LOG_TAG, ">>> launch_service called...");
	app_control_h app_control = NULL;
	if (app_control_create(&app_control)== APP_CONTROL_ERROR_NONE)
	{
		if ((app_control_set_app_id(app_control, SERVICE_APP_NAME) == APP_CONTROL_ERROR_NONE)
			&& (app_control_send_launch_request(app_control, NULL, NULL) == APP_CONTROL_ERROR_NONE))
		{
			dlog_print(DLOG_INFO, LOG_TAG, "App launch request sent!");
		}
		else
		{
			dlog_print(DLOG_ERROR, LOG_TAG, "App launch request sending failed!");
		}
//		if (app_control_destroy(app_control) == APP_CONTROL_ERROR_NONE)
//		{
//			dlog_print(DLOG_INFO, LOG_TAG, "App control destroyed.");
//		}
		// We exit our launcher app, there is no point in keeping it open.
//		ui_app_exit();
	}
	else
	{
		dlog_print(DLOG_ERROR, LOG_TAG, "App control creation failed!");
	}
}

static void stop_service()
{
	dlog_print(DLOG_ERROR, LOG_TAG, ">>> stop_service called...");
	app_control_h app_control = NULL;
	if (app_control_create(&app_control)== APP_CONTROL_ERROR_NONE)
	{
		if ((app_control_set_app_id(app_control, SERVICE_APP_NAME) == APP_CONTROL_ERROR_NONE)
			&& (app_control_add_extra_data(app_control, "service_action", "stop") == APP_CONTROL_ERROR_NONE)
			&& (app_control_send_launch_request(app_control, NULL, NULL) == APP_CONTROL_ERROR_NONE))
		{
			dlog_print(DLOG_INFO, LOG_TAG, "App launch request sent!");
		}
		else
		{
			dlog_print(DLOG_ERROR, LOG_TAG, "App launch request sending failed!");
		}
		if (app_control_destroy(app_control) == APP_CONTROL_ERROR_NONE)
		{
			dlog_print(DLOG_INFO, LOG_TAG, "App control destroyed.");
		}
//		ui_app_exit();
	}
	else
	{
		dlog_print(DLOG_ERROR, LOG_TAG, "App control creation failed!");
	}
}


char fsize[20];
void update_fileSize_info(uib_view1_view_context *user_data){
	char formatted_label[256];
	sprintf(formatted_label, "<font=Tizen:style=Regular font_size=%d>fileSize = %s </font/>", FONT_SIZE, get_dataSize(fsize));
	elm_object_text_set(user_data->file_size, formatted_label);
}

Ecore_Timer* timer = NULL;
void view1_start_stop_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	launch_service();
	if(!timer)
		timer = ecore_timer_loop_add(5, update_fileSize_info, vc);
}

void stop_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info){
	stop_service();
	if(timer)
		ecore_timer_freeze(timer);
}

