/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "view_data.h"
#include "uib_app_manager.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include "sensor_params.h"
#include <sensor.h>
#include <device/power.h>

#include <time.h>

#include <curl/curl.h>
#include <net_connection.h>

#include <system_info.h>


// --------------------------------------- External Functions ---------------------------------------
int uploadAllFiles(const char* dir);
int download_config_file(const char* dir);
void trim(char*);
// --------------------------------------------------------------------------------------------------

int is_running=0;
#define FONT_SIZE 20
#define PROFILE_RESET_N_REQ 5
#define PROFILE_RESET_LAST_TIMELIMIT 30


#define SERVICE_APP_NAME "org.example.rawsensordata"

#define DATA_RECORDING_DURATION 10
#define DATA_RECORDING_INTERVAL 30

typedef struct appdata_t{
	char userid[31];
	uint16_t recording_duration;
	uint16_t recording_interval;
} appdata_t;

appdata_t appdata;

char user_id[256] = "None";


const char* get_lastModified(char *lastModified){
	char fpath[256];
	sprintf(fpath, "stat -c %%y %s%s/ | cut -f 2 -d ' ' | cut -f 1 -d '.'", app_get_data_path(), "current");
	FILE* fp = popen(fpath, "r");
	if(fp) {
		fscanf(fp, "%s", lastModified);
		pclose(fp);
		return lastModified;
	}
	return NULL;
}

const char* get_dataSize(char *fsize){
	char fpath[256];
	sprintf(fpath, "du -sh %s | cut -f 1", app_get_data_path());
	FILE* fp = popen(fpath, "r");
	if(fp) {
		fscanf(fp, "%s", fsize);
		pclose(fp);
		return fsize;
	}
	return NULL;
}

static void launch_service()
{
	if(is_running) return;
	dlog_print(DLOG_ERROR, LOG_TAG, ">>> launch_service called...");
	app_control_h app_control = NULL;
	if (app_control_create(&app_control)== APP_CONTROL_ERROR_NONE)
	{
		if ((app_control_set_app_id(app_control, SERVICE_APP_NAME) == APP_CONTROL_ERROR_NONE)
			&& (app_control_send_launch_request(app_control, NULL, &appdata) == APP_CONTROL_ERROR_NONE))
		{
			dlog_print(DLOG_INFO, LOG_TAG, "App launch request sent!");
			is_running=1;
		}
		else
		{
			dlog_print(DLOG_ERROR, LOG_TAG, "App launch request sending failed!");
		}
//		if (app_control_destroy(app_control) == APP_CONTROL_ERROR_NONE)
//		{
//			dlog_print(DLOG_INFO, LOG_TAG, "App control destroyed.");
//		}
		// We exit our launcher app, there is no point in keeping it open.
//		ui_app_exit();
	}
	else
	{
		dlog_print(DLOG_ERROR, LOG_TAG, "App control creation failed!");
	}
}

static void stop_service()
{
	if(!is_running) return;
	dlog_print(DLOG_ERROR, LOG_TAG, ">>> stop_service called...");
	app_control_h app_control = NULL;
	if (app_control_create(&app_control)== APP_CONTROL_ERROR_NONE)
	{
		if ((app_control_set_app_id(app_control, SERVICE_APP_NAME) == APP_CONTROL_ERROR_NONE)
			&& (app_control_add_extra_data(app_control, "service_action", "stop") == APP_CONTROL_ERROR_NONE)
			&& (app_control_send_launch_request(app_control, NULL, &appdata) == APP_CONTROL_ERROR_NONE))
		{
			dlog_print(DLOG_INFO, LOG_TAG, "App stop request sent!");
			is_running=0;
		}
		else
		{
			dlog_print(DLOG_ERROR, LOG_TAG, "App launch request sending failed!");
		}
		if (app_control_destroy(app_control) == APP_CONTROL_ERROR_NONE)
		{
			dlog_print(DLOG_INFO, LOG_TAG, "App control destroyed.");
		}
//		ui_app_exit();
	}
	else
	{
		dlog_print(DLOG_ERROR, LOG_TAG, "App control creation failed!");
	}
}


char last_modified[256];
char fsize[20];
Eina_Bool update_fileSize_info(void *user_data){
	char formatted_label[256];
	sprintf(formatted_label, "<font=Tizen:style=Regular font_size=%d>DataSize = %s </font/>", FONT_SIZE, get_dataSize(fsize));
	elm_object_text_set(((uib_view1_view_context*)user_data)->file_size, formatted_label);

	sprintf(formatted_label, "<font=Tizen:style=Regular font_size=%d>%s </font/>", FONT_SIZE, get_lastModified(last_modified));
	elm_object_text_set(((uib_view1_view_context*)user_data)->activity, formatted_label);
	return ECORE_CALLBACK_RENEW;
}

Ecore_Timer* upload_timer=NULL;
Eina_Bool upload_data(void *user_data){
	uploadAllFiles(app_get_data_path());
    dlog_print(DLOG_WARN, LOG_TAG, ">>> upload done...");
    upload_timer=NULL;
    return ECORE_CALLBACK_CANCEL;
}

Ecore_Timer* timer = NULL;
void start_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	strncpy(appdata.userid, "subangkar", 31);
	appdata.recording_duration=DATA_RECORDING_DURATION;
	appdata.recording_interval=DATA_RECORDING_INTERVAL;
	launch_service();
	if(!timer)
		timer = ecore_timer_loop_add(5, update_fileSize_info, vc);
	else
		ecore_timer_thaw(timer);
}

void stop_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info){
	stop_service();
	if(timer){
		ecore_timer_freeze(timer);
		ecore_timer_reset(timer);
	}
	char formatted_label[256];
	sprintf(formatted_label, "<font=Tizen:style=Regular font_size=%d>%s </font/>", FONT_SIZE, "STOPPED");
	elm_object_text_set(((uib_view1_view_context*)vc)->activity, formatted_label);
}

void upload_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info){
    dlog_print(DLOG_WARN, LOG_TAG, ">>> upload_onclicked...");
	if(!upload_timer)
		upload_timer = ecore_timer_loop_add(2, upload_data, vc);
	else
		ecore_timer_thaw(upload_timer);
	char formatted_label[256];
	sprintf(formatted_label, "<font=Tizen:style=Regular font_size=%d>DataSize = %s </font/>", FONT_SIZE, get_dataSize(fsize));
	elm_object_text_set(((uib_view1_view_context*)vc)->file_size, formatted_label);
}


void reset_stored_data(char* dir){
	char cmd[256];
    sprintf(cmd, "find %s -maxdepth 1 -type f -name '*.csv' -exec rm -r {} \\;", dir);
    system(cmd);
    sprintf(cmd, "rm -r %scurrent", dir);
    system(cmd);
}


int get_id_from_config(char* config_dir, char* id){
	char filePath[256];
	strcpy(filePath, config_dir);
	if(filePath[strlen(filePath)-1]!='/'){
	strcat(filePath, "/");
	}
	int pathSize = strlen(filePath);
	char* filename = "config.json";
	strcpy(filePath+pathSize, filename);
	FILE *config_file = fopen(filePath, "r");
	if(!config_file){
		dlog_print(DLOG_ERROR, LOG_TAG, "Failed to open file: %s", filePath);
		return 0;
	}
	fgets(id,100,config_file);
	fclose(config_file);
	trim(id);
	if(!strlen(id)) return 0;
	return 1;
}

char *tizenId;
char* load_TizenId()
{    
    int ret;

    ret = system_info_get_platform_string("http://tizen.org/system/tizenid", &tizenId);
    if (ret != SYSTEM_INFO_ERROR_NONE) {
        /* Error handling */
	    dlog_print(DLOG_ERROR, LOG_TAG, "Tizen ID Failed");
        return NULL;
    }

    dlog_print(DLOG_INFO, LOG_TAG, "Tizen ID: %s", tizenId);

	return tizenId;
}

int update_user_id(const char* tizenId, char* config_dir, char* user_id){
	char id[256];
	int id_no = -1;

	char filePath[256];
	strcpy(filePath, config_dir);
	if(filePath[strlen(filePath)-1]!='/'){
	strcat(filePath, "/");
	}
	int pathSize = strlen(filePath);
	char* filename = "config.cfg";
	strcpy(filePath+pathSize, filename);
	FILE *config_file = fopen(filePath, "r");
	if(!config_file){
		dlog_print(DLOG_ERROR, LOG_TAG, "Failed to open file: %s", filePath);
		strcpy(id, "001");
	}
	else{
		fscanf(config_file, "%s", user_id);
		if(strlen(user_id)>4)
			sscanf(user_id+strlen(user_id)-3, "%d", &id_no);
		sprintf(id, "%03d", id_no+1);
		fclose(config_file);
	}
	config_file = fopen(filePath, "w");
	if(!config_file){
		dlog_print(DLOG_ERROR, LOG_TAG, "Failed to modify file: %s", filePath);
		return 0;
	}
	else{
		// sprintf(id, "%03d", id_no+1);
		fprintf(config_file, "%s-%s", tizenId, id);
		sprintf(user_id, "%s-%s", tizenId, id);
		fclose(config_file);
	}
	if(!strlen(id)) return 0;
	return 1;
}

void load_profile_id_to_screen(uib_view1_view_context *vc){
	char* id="None";
	update_user_id(load_TizenId(), app_get_data_path(), user_id);
	if(strlen(user_id)>4)
		id = user_id + strlen(user_id)-3;
	// if(get_id_from_config(app_get_data_path(), id)){
	// 	dlog_print(DLOG_INFO, LOG_TAG, "Read id: %s", id);
	// }
	// else{
	// 	// int error = system_info_get_platform_string("http://tizen.org/system/tizenid", id);
	// 	strcpy(id, "None");
	// }
	// if (strcmp(id, user_id)){
	// 	strcpy(user_id, id);
		stop_service();
		char formatted_label[256];
		sprintf(formatted_label, "<font=Tizen:style=Regular font_size=%d>Profile = %s </font/>", FONT_SIZE, id);
		elm_object_text_set(((uib_view1_view_context*)vc)->profile_id, formatted_label);
		reset_stored_data(app_get_data_path());
	// }
}

int nProfileClicked = -1;
time_t last_profClickedTimestamp = 0;
void fetch_profile_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info){
	// reset clicks older than certain time threshold
	if(nProfileClicked != -1 && (time(NULL) - last_profClickedTimestamp) > PROFILE_RESET_LAST_TIMELIMIT)
		nProfileClicked = 0;
	nProfileClicked = (nProfileClicked + 1) % PROFILE_RESET_N_REQ;
	if(!(nProfileClicked % PROFILE_RESET_N_REQ))
		load_profile_id_to_screen(vc);
	// // if(!download_config_file(app_get_data_path()))	{
	// if(update_user_id(load_TizenId(), app_get_data_path(), user_id))	{
	// 	dlog_print(DLOG_INFO, LOG_TAG, "Updated Config");
	// 	load_profile_id_to_screen(vc);
	// }
	// else
	// 	dlog_print(DLOG_ERROR, LOG_TAG, "Config Not Changed");
	last_profClickedTimestamp = time(NULL);
}
